services:
  - type: web
    name: techni-social-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://user:1234@techni.jz092wg.mongodb.net/techni-social?retryWrites=true&w=majority&appName=Techni
      - key: JWT_SECRET
        value: techni-beer-sheva-super-secret-jwt-key-2024-change-me-64chars-min
      - key: ADMIN_CODE
        value: "1324"
      - key: ADMIN_SECRET_TOKEN
        value: techni-admin-secret-token-2024-change-this-now
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password
      - key: CLOUDINARY_CLOUD_NAME
        value: dmhkzdevt
      - key: CLOUDINARY_API_KEY
        value: "334642945362434"
      - key: CLOUDINARY_API_SECRET
        value: 17-hbIBVQHJF-UmjZ14BSuHT6Ss
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
